FinalMLP_movielenslatest_x1_004_498f3e4f:
    batch_size: 4096
    dataset_id: csv_default
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    eval_interval: 1
    feature_specs: null
    fs1_context: []
    fs2_context: []
    fs_hidden_units: [800]
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    mlp1_batch_norm: true
    mlp1_dropout: 0.4
    mlp1_hidden_activations: relu
    mlp1_hidden_units: [400]
    mlp2_batch_norm: true
    mlp2_dropout: 0.2
    mlp2_hidden_activations: relu
    mlp2_hidden_units: [800]
    model: FinalMLP
    model_id: FinalMLP_default
    model_root: ./output/FinalMLP/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_heads: 10
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_fs: true
    verbose: 1


FinalMLP_criteo_x1_004_d5d36917:
    batch_size: 4096
    dataset_id: criteo_x1_49102577
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_interval: 1
    feature_specs: null
    fs1_context: [I1, I2, I3, I4, I5, I6, I7, I8, I9, I10, I11, I12, I13]
    fs2_context: [C6]
    fs_hidden_units: [800]
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    mlp1_batch_norm: true
    mlp1_dropout: 0.2
    mlp1_hidden_activations: relu
    mlp1_hidden_units: [400, 400, 400]
    mlp2_batch_norm: true
    mlp2_dropout: 0.3
    mlp2_hidden_activations: relu
    mlp2_hidden_units: [1000]
    model: FinalMLP
    model_id: FinalMLP_default
    model_root: ./output/FinalMLP/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_heads: 200
    num_workers: 0
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_fs: true
    verbose: 0